name: Docker Image CI

on:
  release:
    types: [released]

env: 
  TRAPS_REL: ${{ github.event.release.tag_name }}

jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push engine
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/camera_traps_engine:${{ env.TRAPS_REL }}
          build-args: TRAPS_REL=${{ env.TRAPS_REL }}
      - name: Build and push pyevents
        uses: docker/build-push-action@v5
        with:
          context: https://github.com/tapis-project/event-engine.git#:pyevents
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/pyevents
      - name: Build and push camera_traps_py
        uses: docker/build-push-action@v5
        with:
          context: src/python
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/camera_traps_py:${{ env.TRAPS_REL }}
      - name: Build and push image_scoring_plugin
        uses: docker/build-push-action@v5
        with:
          context: external_plugins/image_scoring_plugin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/image_scoring_plugin_py:${{ env.TRAPS_REL }}
          build-args: TRAPS_REL=${{ env.TRAPS_REL }}
      - name: Build and push image_generating_plugin
        uses: docker/build-push-action@v5
        with:
          context: external_plugins/image_generating_plugin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/image_generating_plugin_py:${{ env.TRAPS_REL }}
          build-args: TRAPS_REL=${{ env.TRAPS_REL }}
      - name: Build and push power_measuring_plugin
        uses: docker/build-push-action@v5
        with:
          context: external_plugins/power_measuring_plugin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: skhuvis/power_measuring_plugin_py:${{ env.TRAPS_REL }}
          build-args: TRAPS_REL=${{ env.TRAPS_REL }}
